feat: support object types in array
jsonnet-libs/k8s pull request #180
Opened 2022-06-13 01:48 UTC by xuanyue202

work on description

2022-06-13 19:12 UTC, xvzf commented
@xuanyue202 it looks good from a first glance. Checking the backward compatibility now. This likely fixes #34

2022-06-13 20:10 UTC, xvzf requested changes
I found a couple of things. With the suggested change, we limit the changes to some fields just argument changes (see attached diff). I think it's a fair "tradeoff". Waiting for some other reviews as well since this could have some unforeseen side-effects

```diff
---
>     '#withError':: d.fn(help='"Error describes any problems reconciling the Spec.ConfigSource to the Active config. Errors may occur, for example, attempting to checkpoint Spec.ConfigSource to the local Assigned record, attempting to checkpoint the payload associated with Spec.ConfigSource, attempting to load or validate the Assigned config, etc. Errors may occur at different points while syncing config. Earlier errors (e.g. download or checkpointing errors) will not result in a rollback to LastKnownGood, and may resolve across Kubelet retries. Later errors (e.g. loading or validating a checkpointed config) will result in a rollback to LastKnownGood. In the latter case, it is usually possible to resolve the error by fixing the config assigned in Spec.ConfigSource. You can find additional information for debugging by searching the error message in the Kubelet log. Error is a human-readable description of the error state; machines can check whether or not Error is empty, but should not rely on the stability of the Error text across Kubelet versions."', args=[d.arg(name='Error', type=d.T.string)]),
>     withError(Error): { config+: { 'error': Error } },
diff -r --exclude .git /tmp/github.com/jsonnet-libs/k8s-libsonnet/1.21/_gen/core/v1/portStatus.libsonnet /output/github.com/jsonnet-libs/k8s-libsonnet/1.21/_gen/core/v1/portStatus.libsonnet
4,5c4,5
```

2022-06-14 02:28 UTC, xuanyue202 commented on pkg/model/modifiers.go
> +		}
have changed 'arrayWith' back to 'with'

2022-06-14 02:32 UTC, xuanyue202 commented
> 

have changed withError(Error) back to withError(err)

2022-06-14 11:29 UTC, xvzf approved these changes
lgtm, nice job and thx for the contribution @xuanyue202

2022-06-14 11:31 UTC, merged