Bump Crossplane provider-nop to v0.2.0
jsonnet-libs/k8s pull request #335
Opened 2023-07-24 11:50 UTC by jvrplmlmn

https://github.com/crossplane-contrib/provider-nop/releases/tag/v0.2.0

2023-07-25 10:37 UTC, iainlane approved these changes

2023-07-25 15:11 UTC, xvzf requested changes

2023-07-25 15:11 UTC, xvzf commented on libs/crossplane/config.jsonnet
>      },
You might want to add a new entry when there are breaking changes between v0.1.1 and v0.2.0

2023-07-31 13:21 UTC, xvzf approved these changes

2023-08-01 17:48 UTC, julienduchesne approved these changes

2023-08-01 17:48 UTC, merged